# Generated by Django 2.0.2 on 2018-11-02 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRecords',
        ),
    ]
