# Generated by Django 2.0.2 on 2018-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20181124_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='home_info',
        ),
        migrations.AddField(
            model_name='service',
            name='service_info_long',
            field=models.CharField(default='Shows up in the individual services page', max_length=400),
        ),
        migrations.AddField(
            model_name='service',
            name='service_info_short',
            field=models.CharField(default='Shows up in the individual services page', max_length=400),
        ),
    ]
