# Generated by Django 2.0.2 on 2018-10-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Getassist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myrego', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField()),
                ('vehicleMake', models.CharField(max_length=100)),
                ('vehicleModel', models.CharField(max_length=100)),
                ('myName', models.CharField(max_length=100)),
                ('myLocation', models.CharField(max_length=200)),
                ('mynotes', models.TextField()),
            ],
        ),
    ]
